theme: jekyll-theme-minimal
title: Zhendong Wang
description: Software Engineering Researcher
logo: https://github.com/zhendow/zhendow.github.io/blob/main/resources/Headshot.jpeg
show_downloads: false
