theme: jekyll-theme-minimal
title: Zhendong Wang
description: Software Engineering Researcher
logo: <center>https://github.com/zhendow/zhendow.github.io/blob/main/resources/Headshot.jpeg?raw=true</center>
show_downloads: false
