theme: jekyll-theme-minimal
title: Zhendong Wang
description: Software Engineering Researcher \n zhendow[at]uci[dot]edu
logo: https://github.com/zhendow/zhendow.github.io/blob/main/resources/Headshot.jpeg?raw=true
show_downloads: false
